services:
  mysql:
    image: docker.io/library/mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: test
       MYSQL_DATABASE: customer_db
       MYSQL_USER: my_user
       MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  postgresql:
    image: docker.io/library/postgres:latest
    environment:
       POSTGRES_DB: product_db
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  eureka:
    image: "localhost/eureka"
    build: ./eureka #image build
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=dev
    networks:
      - common
  gateway:
    image: "localhost/gateway"
    ports:
      - "8090:8090"
    networks:
      - common
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8888/eureka/
    depends_on:
      - eureka
  productservice:
    image: "localhost/productservice"
    ports:
      - "8080:8080"
    networks:
      - common
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8888/eureka/
    depends_on:
      - eureka
  customerservice:
    image: "localhost/customerservice"
    ports:
      - "8081:8081"
    networks:
      - common
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8888/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/customer_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=my_user
      - SPRING_DATASOURCE_PASSWORD=test
    depends_on:
      - eureka
  configserver:
    image: "localhost/configserver"
    ports:
      - "8001:8001"
    networks:
      - common
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8888/eureka/
volumes:
  mysql_data:
  postgres_data:

networks:
  common:
    driver: bridge