spring:
  config:
    import: "optional:configserver:"
  application:
    name: customerservice
  cloud:
    config:
      uri: http://localhost:8001
      profile: local
      label: main

# http://localhost:8001/customerservice/dev/master